image: Visual Studio 2022

build_script:
  - cmd: .\build_script.bat
  
after_build:
  - ps: py .\zip_script.py
 
artifacts:
  - path: CFGEditor.zip
  
environment:
  ATARISMWC_AUTH_KEY:
    secure: Ajcj3MoPREPDvB2WI67C5JWz3iVRTMJIeTtfvWEc6vk=

deploy:
  - provider: Webhook
    on:
      branch: master
    authorization: Basic $(ATARISMWC_AUTH_KEY)
    url: https://www.atarismwc.com/upload_cfgeditor.php
    request_timeout: 10