image: Visual Studio 2022

build_script:
  - cmd: .\build_script.bat
  
after_build:
  - ps: py .\zip_script.py
 
artifacts:
  - path: CFGEditor.zip

deploy:
  provider: FTP
  protocol: sftp
  host: www.atarismwc.com
  folder: html/cfgeditorplusplus/
  username: pi
  password:
    secure: 5EUQJJ1H2QhydG9QQsaKaQ==